"use client";
import {useEffect,useRef,useState} from "react";
import {cars,short,Car} from "./data";

function ModelCard({car}:{car:Car}){return <article className="bmw-model-card"><a href={`/cars/${car.slug}`}><figure><img src={car.image} alt={`${car.brand} ${car.model}`} loading="lazy"/><span>{car.badge}</span></figure><small>{car.brand.toUpperCase()} · {car.year}</small><h3>{car.model}</h3><p>{car.variant}</p><div><b>{short(car.price)}</b><span>{car.power} · {car.range}</span></div></a></article>}

export default function BMWHome(){const [signed,setSigned]=useState(false),[videoError,setVideoError]=useState(false),[paused,setPaused]=useState(false);const heroVideo=useRef<HTMLVideoElement>(null);useEffect(()=>setSigned(!!localStorage.getItem("max-session")),[]);function toggleFilm(){const video=heroVideo.current;if(!video)return;if(video.paused){void video.play().then(()=>setPaused(false)).catch(()=>setPaused(true));}else{video.pause();setPaused(true)}}return <>
 <section className="m8-hero is-ready" style={{backgroundImage:"url(/bmw-m8-home-poster.jpg)"}} aria-labelledby="m8-title">
  {!videoError&&<video ref={heroVideo} autoPlay muted loop playsInline preload="metadata" poster="/bmw-m8-home-poster.jpg" onError={()=>setVideoError(true)} aria-label="BMW M8 Competition Coupe driving film"><source src="/bmw-m8-home.mp4" type="video/mp4"/></video>}
  {videoError&&<img className="m8-hero-image" src="/bmw-m8-home-poster.jpg" alt="BMW M8 Competition Coupe in a premium blue finish"/>}
  <div className="m8-ambient" aria-hidden="true"/><div className="m8-word" aria-hidden="true">M8</div>
    <div className="m8-kicker"><span>MAX CARS / PERFORMANCE 01</span><b>REAL DRIVING / CLOSED TRACK</b></div>
    <div className="m8-copy"><small>THE BMW M8 COMPETITION COUPE</small><h1 id="m8-title">Command<br/>every road.</h1><p>Exceptional design, grand-touring comfort and unmistakable M performance in one considered vehicle experience.</p><nav aria-label="BMW M8 actions"><a className="m8-primary" href="/cars?brand=BMW">Explore BMW</a><a href="/max-3d">Open MAX 3D</a></nav></div>
    <aside className="m8-specs" aria-label="BMW M8 highlights"><span><b>625 hp</b><small>Output</small></span><span><b>3.2 s</b><small>0–100 km/h</small></span><span><b>M xDrive</b><small>Drivetrain</small></span></aside>
    <div className="m8-controls"><span><b>01</b> / 01</span><button type="button" onClick={toggleFilm} aria-label={paused?"Play BMW M8 film":"Pause BMW M8 film"}>{paused?"▶":"Ⅱ"}</button><a href="#discover-home" aria-label="Continue to vehicle discovery">↓</a></div>
  <small className="m8-source">BMW M8 Competition media · BMW Group PressClub</small>
 </section>
 <section className="bmw-find" id="discover-home"><h2>Find your MAX.</h2><div><article><span>⌕</span><h3>Find a new car.</h3><a href="/cars?condition=new">Search now</a></article><article><span>◷</span><h3>Book a test drive.</h3><a href={signed?"/dashboard/bookings":"/login?returnTo=/dashboard/bookings"}>Request a test drive</a></article><article><span>⌖</span><h3>Find local support.</h3><a href="/location">Explore locations</a></article></div></section>
 <section className="bmw-visual-garage"><header><div><small>VISUAL GARAGE / VERIFIED MEDIA</small><h2>Every angle tells a different story.</h2></div><a href="/cars">Explore all vehicles →</a></header><div className="bmw-visual-grid"><a href="/cars/audi-rs-etron-gt"><img src="/vehicles/audi-rs-etron-gt/gallery-1.webp" alt="Audi RS e-tron GT front view" loading="lazy"/><span><b>Audi RS e-tron GT</b><small>Electric performance / front view</small></span></a><a href="/cars/bmw-i7-xdrive60"><img src="/vehicles/bmw-i7-xdrive60/gallery-2.webp" alt="BMW i7 rear three-quarter view" loading="lazy"/><span><b>BMW i7</b><small>Luxury electric / rear view</small></span></a><a href="/cars/byd-sealion-7"><img src="/vehicles/byd-sealion-7/gallery-3.webp" alt="BYD Sealion 7 exterior view" loading="lazy"/><span><b>BYD Sealion 7</b><small>Electric SUV / exterior view</small></span></a><a href="/cars/skoda-kodiaq"><img src="/vehicles/skoda-kodiaq/gallery-1.webp" alt="Skoda Kodiaq front view" loading="lazy"/><span><b>Skoda Kodiaq</b><small>Family SUV / front view</small></span></a></div></section>
 <section className="bmw-video-rail"><header><div><small>MORE TO WATCH</small><h2>Real cars. Real places.</h2></div><p>Watch the range move through the city in a cinematic driving film.</p></header><div><figure><video autoPlay muted loop playsInline preload="metadata" poster="/explore-cars-cinematic-poster.jpg" controls aria-label="Cars driving through a city"><source src="/explore-cars-cinematic.mp4" type="video/mp4"/></video><figcaption>Explore the range / city drive</figcaption></figure></div></section>
 <section className="bmw-ownership-hub"><header><div><small>OWNERSHIP, MADE CLEAR</small><h2>Everything after “buy”.</h2></div><p>Move from discovery to the road with connected tools for the decisions that matter.</p></header><div className="bmw-ownership-grid"><a href="/finance"><b>01</b><strong>Plan the payment</strong><span>Compare indicative monthly costs.</span><em>Explore finance →</em></a><a href="/location"><b>02</b><strong>Find a trusted centre</strong><span>Locate service, delivery and support.</span><em>Find a location →</em></a><a href="/sell-your-car"><b>03</b><strong>Value your current car</strong><span>Create a verified listing in five steps.</span><em>Start valuation →</em></a><a href="/support"><b>04</b><strong>Keep help close</strong><span>Get precise answers when you need them.</span><em>Visit support →</em></a></div></section>
 <nav className="bmw-model-nav"><span>EXPLORE THE RANGE</span>{[["All models","/cars"],["Electric","/cars?fuel=electric"],["Luxury","/cars?category=luxury"],["Performance","/cars?category=performance"],["SUV","/cars?body=suv"]].map(x=><a key={x[0]} href={x[1]}>{x[0]}</a>)}</nav>
 <section className="bmw-stories">{cars.slice(1,4).map((car,i)=><article className={i%2?"reverse":""} key={car.id}><figure><img src={car.image} alt={`${car.brand} ${car.model}`}/></figure><div><small>{car.brand.toUpperCase()} / {car.category.toUpperCase()}</small><h2>{car.model}</h2><p>{i===0?"Electric performance, resolved with effortless range and a cabin designed around the driver.":i===1?"A new expression of grand touring—precise, composed and unmistakably confident.":"Space, capability and sophisticated technology for every road ahead."}</p><dl><span><b>{car.power}</b>Power</span><span><b>{car.range}</b>{car.fuel==="electric"?"Range":"Efficiency"}</span><span><b>{short(car.price)}</b>From*</span></dl><a className="red" href={`/cars/${car.slug}`}>Know more</a></div></article>)}</section>
 <section className="bmw-range"><header><div><small>SELECTED FOR YOU</small><h2>Explore more extraordinary cars.</h2></div><a href="/cars">View all models →</a></header><div>{cars.slice(0,6).map(c=><ModelCard key={c.id} car={c}/>)}</div></section>
 <section className="bmw-offer"><div><small>MAX CARS FINANCIAL SERVICES</small><h2>Special ownership offers.</h2><p>Explore indicative monthly payments, trade-in value and total ownership cost before speaking with a finance provider.</p><a className="red" href="/finance">Calculate finance</a></div><aside><span>ESTIMATED EMI</span><b>From ₹29,999<small>/month*</small></b><p>Estimates only. Final rates and approval depend on the selected finance provider.</p></aside></section>
 <section className="bmw-newsletter"><div><small>MAX CARS JOURNAL</small><h2>Stay ahead of the road.</h2></div><a href="/guides">Read the latest guides →</a></section>
 </>}
