"use client";
import {useEffect,useState} from "react";
import {cars,short,Car} from "./data";

function ModelCard({car}:{car:Car}){return <article className="bmw-model-card"><a href={`/cars/${car.slug}`}><figure><img src={car.image} alt={`${car.brand} ${car.model}`} loading="lazy"/><span>{car.badge}</span></figure><small>{car.brand.toUpperCase()} · {car.year}</small><h3>{car.model}</h3><p>{car.variant}</p><div><b>{short(car.price)}</b><span>{car.power} · {car.range}</span></div></a></article>}

function GarageMatch(){const [budget,setBudget]=useState(5000000),[usage,setUsage]=useState("city"),[body,setBody]=useState("any"),[ready,setReady]=useState(false);const matches=cars.filter(car=>car.price<=budget&&(body==="any"||car.body===body)).sort((a,b)=>usage==="performance"?parseInt(b.power)-parseInt(a.power):usage==="family"?b.seats-a.seats:a.price-b.price).slice(0,3);return <section className="garage-match" aria-labelledby="garage-match-title"><header><small>GARAGE MATCH / GUIDED FINDER</small><h2 id="garage-match-title">A better shortlist starts with your life.</h2><p>Set three priorities and we’ll recommend genuine matches from the MAX CARS catalogue.</p></header><form onSubmit={event=>{event.preventDefault();setReady(true)}}><label>Maximum budget<select value={budget} onChange={event=>setBudget(Number(event.target.value))}><option value="2000000">Up to ₹20 lakh</option><option value="5000000">Up to ₹50 lakh</option><option value="10000000">Up to ₹1 crore</option><option value="100000000">No fixed limit</option></select></label><label>Primary usage<select value={usage} onChange={event=>setUsage(event.target.value)}><option value="city">Daily city driving</option><option value="family">Family and touring</option><option value="performance">Performance driving</option></select></label><label>Preferred body type<select value={body} onChange={event=>setBody(event.target.value)}><option value="any">Open to suggestions</option><option value="suv">SUV</option><option value="sedan">Sedan</option><option value="coupe">Coupé</option><option value="mpv">MPV</option></select></label><button className="red">Find my matches →</button></form>{ready&&<div className="garage-results" aria-live="polite">{matches.length?matches.map(car=><a href={`/cars/${car.slug}`} key={car.id}><img src={car.image} alt=""/><span><small>{car.brand}</small><b>{car.model}</b><em>{usage==="family"?`${car.seats} seats and ${car.body} practicality`:usage==="performance"?`${car.power} with ${car.drive}`:`Within budget at ${short(car.price)}`}</em></span></a>):<article><b>No exact match yet.</b><a href="/cars">Open all filters</a></article>}</div>}</section>}

export default function BMWHome(){const [signed,setSigned]=useState(false),[videoError,setVideoError]=useState(false);useEffect(()=>setSigned(!!localStorage.getItem("max-session")),[]);return <>
 <section className="m8-hero is-ready" style={{backgroundImage:"url(/vehicles/bmw-m2-g87/P90553555.jpg)"}} aria-labelledby="m8-title">
  {!videoError&&<video autoPlay muted loop playsInline preload="auto" poster="/vehicles/bmw-m2-g87/P90553555.jpg" onError={()=>setVideoError(true)} aria-label="BMW M8 Competition Coupe driving film"><source src="/bmw-m8-home.mp4" type="video/mp4"/></video>}
  {videoError&&<img className="m8-hero-image" src="/vehicles/bmw-m2-g87/P90553555.jpg" alt="BMW performance coupe in a premium architectural setting"/>}
  <div className="m8-ambient" aria-hidden="true"/>
    <div className="m8-kicker"><span>MAX CARS / PERFORMANCE 01</span><b>REAL DRIVING / CLOSED TRACK</b></div>
    <div className="m8-copy"><small>MAX CARS / EXPLORE. CONFIGURE. DRIVE.</small><h1 id="m8-title">The drive<br/>starts here.</h1><p>Explore exceptional cars, build your perfect specification and move confidently from discovery to ownership.</p><nav aria-label="MAX CARS hero actions"><a className="m8-primary" href="/cars">Explore Cars</a><a href="/max-3d">Enter MAX 3D</a><a href="#garage-match">Find My Car</a></nav></div>
    <aside className="m8-specs" aria-label="BMW M8 highlights"><span><b>625 hp</b><small>Output</small></span><span><b>3.2 s</b><small>0–100 km/h</small></span><span><b>M xDrive</b><small>Drivetrain</small></span></aside>
  <small className="m8-source">BMW M8 Competition media · BMW Group PressClub</small>
 </section>
 <section className="bmw-find" id="discover-home"><h2>Find your MAX.</h2><div><article><span>⌕</span><h3>Find a new car.</h3><a href="/cars?condition=new">Search now</a></article><article><span>◷</span><h3>Book a test drive.</h3><a href={signed?"/dashboard/bookings":"/login?returnTo=/dashboard/bookings"}>Request a test drive</a></article><article><span>⌖</span><h3>Find local support.</h3><a href="/location">Explore locations</a></article></div></section>
 <section className="media-studio" aria-labelledby="media-studio-title"><header><div><small>MAX STUDIO / VERIFIED MEDIA</small><h2 id="media-studio-title">See the drive from every angle.</h2></div><p>High-resolution films and official vehicle photography, curated for a closer first look.</p></header><div className="media-studio-grid"><a className="media-studio-film" href="/cars"><video autoPlay muted loop playsInline preload="metadata" poster="/max-cars-luxury-city-poster.jpg" aria-label="Luxury cars moving through a city"><source src="/max-cars-luxury-city.mp4" type="video/mp4"/></video><span><small>CINEMATIC FILM</small><b>Move through the range.</b><em>Explore all cars ↗</em></span></a><a href="/cars/audi-rs-etron-gt"><img src="/vehicles/audi-rs-etron-gt/gallery-1.webp" alt="Audi RS e-tron GT front three-quarter view" loading="lazy"/><span><small>ELECTRIC PERFORMANCE</small><b>Audi RS e-tron GT</b><em>Open vehicle ↗</em></span></a><a href="/cars/bmw-i7-xdrive60"><img src="/vehicles/bmw-i7-xdrive60/gallery-2.webp" alt="BMW i7 rear three-quarter view" loading="lazy"/><span><small>GRAND TOURING</small><b>BMW i7</b><em>Open vehicle ↗</em></span></a></div></section>
 <div id="garage-match"><GarageMatch/></div>
 <section className="bmw-visual-garage"><header><div><small>VISUAL GARAGE / VERIFIED MEDIA</small><h2>Every angle tells a different story.</h2></div><a href="/cars">Explore all vehicles →</a></header><div className="bmw-visual-grid"><a href="/cars/audi-rs-etron-gt"><img src="/vehicles/audi-rs-etron-gt/gallery-1.webp" alt="Audi RS e-tron GT front view" loading="lazy"/><span><b>Audi RS e-tron GT</b><small>Electric performance / front view</small></span></a><a href="/cars/bmw-i7-xdrive60"><img src="/vehicles/bmw-i7-xdrive60/gallery-2.webp" alt="BMW i7 rear three-quarter view" loading="lazy"/><span><b>BMW i7</b><small>Luxury electric / rear view</small></span></a><a href="/cars/byd-sealion-7"><img src="/vehicles/byd-sealion-7/gallery-3.webp" alt="BYD Sealion 7 exterior view" loading="lazy"/><span><b>BYD Sealion 7</b><small>Electric SUV / exterior view</small></span></a><a href="/cars/skoda-kodiaq"><img src="/vehicles/skoda-kodiaq/gallery-1.webp" alt="Skoda Kodiaq front view" loading="lazy"/><span><b>Skoda Kodiaq</b><small>Family SUV / front view</small></span></a></div></section>
 <section className="bmw-video-rail"><header><div><small>MORE TO WATCH</small><h2>Real cars. Real places.</h2></div><p>Watch the range move through the city in a cinematic driving film.</p></header><div><figure><video autoPlay muted loop playsInline preload="metadata" poster="/explore-cars-cinematic-poster.jpg" controls aria-label="Cars driving through a city"><source src="/explore-cars-cinematic.mp4" type="video/mp4"/></video><figcaption>Explore the range / city drive</figcaption></figure></div></section>
 <section className="bmw-ownership-hub"><header><div><small>OWNERSHIP, MADE CLEAR</small><h2>Everything after “buy”.</h2></div><p>Move from discovery to the road with connected tools for the decisions that matter.</p></header><div className="bmw-ownership-grid"><a href="/finance"><b>01</b><strong>Plan the payment</strong><span>Compare indicative monthly costs.</span><em>Explore finance →</em></a><a href="/location"><b>02</b><strong>Find a trusted centre</strong><span>Locate service, delivery and support.</span><em>Find a location →</em></a><a href="/sell-your-car"><b>03</b><strong>Value your current car</strong><span>Create a verified listing in five steps.</span><em>Start valuation →</em></a><a href="/support"><b>04</b><strong>Keep help close</strong><span>Get precise answers when you need them.</span><em>Visit support →</em></a></div></section>
 <nav className="bmw-model-nav"><span>EXPLORE THE RANGE</span>{[["All models","/cars"],["Electric","/cars?fuel=electric"],["Luxury","/cars?category=luxury"],["Performance","/cars?category=performance"],["SUV","/cars?body=suv"]].map(x=><a key={x[0]} href={x[1]}>{x[0]}</a>)}</nav>
 <section className="bmw-stories">{cars.slice(1,4).map((car,i)=><article className={i%2?"reverse":""} key={car.id}><figure><img src={car.image} alt={`${car.brand} ${car.model}`}/></figure><div><small>{car.brand.toUpperCase()} / {car.category.toUpperCase()}</small><h2>{car.model}</h2><p>{i===0?"Electric performance, resolved with effortless range and a cabin designed around the driver.":i===1?"A new expression of grand touring—precise, composed and unmistakably confident.":"Space, capability and sophisticated technology for every road ahead."}</p><dl><span><b>{car.power}</b>Power</span><span><b>{car.range}</b>{car.fuel==="electric"?"Range":"Efficiency"}</span><span><b>{short(car.price)}</b>From*</span></dl><a className="red" href={`/cars/${car.slug}`}>Know more</a></div></article>)}</section>
 <section className="bmw-range"><header><div><small>SELECTED FOR YOU</small><h2>Explore more extraordinary cars.</h2></div><a href="/cars">View all models →</a></header><div>{cars.slice(0,6).map(c=><ModelCard key={c.id} car={c}/>)}</div></section>
 <section className="bmw-offer"><div><small>MAX CARS FINANCIAL SERVICES</small><h2>Special ownership offers.</h2><p>Explore indicative monthly payments, trade-in value and total ownership cost before speaking with a finance provider.</p><a className="red" href="/finance">Calculate finance</a></div><aside><span>ESTIMATED EMI</span><b>From ₹29,999<small>/month*</small></b><p>Estimates only. Final rates and approval depend on the selected finance provider.</p></aside></section>
 <section className="bmw-newsletter"><div><small>MAX CARS JOURNAL</small><h2>Stay ahead of the road.</h2></div><a href="/guides">Read the latest guides →</a></section>
 </>}
