"use client";
import {useEffect,useMemo,useState} from "react";

type Session={name:string;email:string};
type Profile={phone:string;dob:string;city:string;postcode:string;dealer:string;brands:string;budget:string;body:string;fuel:string;memberSince:string};
const defaults:Profile={phone:"",dob:"",city:"Hyderabad",postcode:"500033",dealer:"MAX CARS Jubilee Hills",brands:"BMW, Porsche, Mercedes-Benz",budget:"₹50 lakh–₹1 crore",body:"SUV, Coupe",fuel:"Electric, Petrol",memberSince:"August 2026"};
function ProfileIcon({name}:{name:string}){const d:Record<string,string>={heart:"M12 20s-7-4.4-9-9.3C1.5 5.8 7.3 3 12 7.6 16.7 3 22.5 5.8 21 10.7 19 15.6 12 20Z",compare:"M4 7h14m0 0-3-3m3 3-3 3M20 17H6m0 0 3-3m-3 3 3 3",calendar:"M4 6h16v15H4zM8 3v6m8-6v6M4 11h16",cube:"M12 3 21 8 12 13 3 8 12 3Zm-9 5v9l9 5 9-5V8M12 13v9",car:"M4 15l2-6h12l2 6M3 15h18v5h-3v-2H6v2H3zM7 15h.01M17 15h.01",receipt:"M6 3h12v18l-3-2-3 2-3-2-3 2V3Zm3 5h6m-6 4h6",help:"M9.5 9a2.8 2.8 0 1 1 4.2 2.4c-1.1.6-1.7 1.1-1.7 2.6m0 4h.01M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z",bell:"M6 16h12l-2-3V9a4 4 0 0 0-8 0v4l-2 3Zm4 3h4"};return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={d[name]||d.car}/></svg>}

export default function ProfileDashboardV2(){
  const [session,setSession]=useState<Session>({name:"MAX Member",email:""}),[profile,setProfile]=useState(defaults),[avatar,setAvatar]=useState(""),[editing,setEditing]=useState(false),[notice,setNotice]=useState("");
  const [counts,setCounts]=useState({saved:0,compare:0,bookings:0,configs:0,listings:0,orders:0,tickets:0,notifications:1});
  useEffect(()=>{const timer=window.setTimeout(()=>{const active=JSON.parse(localStorage.getItem("max-session")||"null") as Session|null;if(!active){location.replace("/login?returnTo=/profile");return}setSession(active);setAvatar(localStorage.getItem("max-avatar")||"");setProfile({...defaults,...JSON.parse(localStorage.getItem("max-profile")||"{}")});setCounts({saved:JSON.parse(localStorage.getItem("max-favs")||"[]").length,compare:JSON.parse(localStorage.getItem("max-compare")||"[]").length,bookings:JSON.parse(localStorage.getItem("max-bookings")||"[]").length,configs:JSON.parse(localStorage.getItem("max-3d-configs")||"[]").length,listings:JSON.parse(localStorage.getItem("max-listings")||"[]").length,orders:JSON.parse(localStorage.getItem("max-orders")||"[]").length,tickets:JSON.parse(localStorage.getItem("max-tickets")||"[]").length,notifications:1})},0);return()=>window.clearTimeout(timer)},[]);
  const initials=useMemo(()=>session.name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase(),[session.name]);
  const upload=(file?:File)=>{if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>3*1024*1024){setNotice("Choose a JPG, PNG or WebP under 3 MB.");return}const reader=new FileReader();reader.onload=()=>{const value=String(reader.result);localStorage.setItem("max-avatar",value);setAvatar(value);dispatchEvent(new Event("max-state"))};reader.readAsDataURL(file)};
  const save=(event:React.FormEvent)=>{event.preventDefault();localStorage.setItem("max-profile",JSON.stringify(profile));localStorage.setItem("max-session",JSON.stringify(session));dispatchEvent(new Event("max-state"));setEditing(false);setNotice("Profile preferences saved on this device.")};
  const cards=[
    ["Saved cars",counts.saved,"/favourites","heart"],["Active comparisons",counts.compare,"/compare","compare"],["Test drives",counts.bookings,"/dashboard/bookings","calendar"],["Configurations",counts.configs,"/max-3d/saved","cube"],["My car listings",counts.listings,"/profile/listings","car"],["Reservations",counts.orders,"/orders","receipt"],["Support tickets",counts.tickets,"/support#support-tracking","help"],["Notifications",counts.notifications,"/notifications","bell"],
  ] as const;
  const quick=[
    ["Recently viewed","Return to vehicles you inspected","/cars?recent=1"],["Finance applications","Review estimates and application status","/finance"],["Location preferences","Saved centres, city and recent searches","/location"],["Account security","Password, sessions and privacy controls","/profile/security"],["Payment methods","Provider-ready payment preferences","/profile/payments"],["Help and support","Track tickets and report catalogue issues","/support"],
  ] as const;
  return <main className="profile-dashboard-v2">
    <section className="profile-hero-v2"><img src="/vehicles/bmw-m2-g87/P90553555.jpg" alt="BMW M2 in a premium outdoor setting"/><div className="profile-hero-shade"/><div className="profile-identity"><div className="profile-photo">{avatar?<img src={avatar} alt={`${session.name} profile`}/>:initials}<i/></div><div><small>PRIVATE GARAGE / MAX MEMBER</small><h1>{session.name}</h1><p>{session.email||"Add an email address"} · Member since {profile.memberSince}</p><nav><button onClick={()=>setEditing(true)}>Edit Profile</button><a href="/cars">Explore Cars</a></nav></div></div><div className="profile-membership"><b>MAX</b><span>Verified member profile</span><small>Preferences stored locally in this demonstration</small></div></section>
    {notice&&<p className="profile-notice" role="status">{notice}</p>}
    <section className="profile-summary-v2"><header><small>01 / YOUR ACTIVITY</small><h2>Everything around your next drive.</h2></header><div>{cards.map(([label,count,href,icon])=><a href={href} key={label}><i><ProfileIcon name={icon}/></i><strong>{count}</strong><span>{label}</span><em>Open →</em></a>)}</div></section>
    <section className="profile-content-v2"><article className="profile-overview"><header><div><small>02 / PROFILE</small><h2>Buyer preferences</h2></div><button onClick={()=>setEditing(true)}>Edit details</button></header><dl><div><dt>Mobile</dt><dd>{profile.phone||"Not added"}</dd></div><div><dt>Preferred city</dt><dd>{profile.city} · {profile.postcode}</dd></div><div><dt>Preferred dealer</dt><dd>{profile.dealer}</dd></div><div><dt>Preferred brands</dt><dd>{profile.brands}</dd></div><div><dt>Budget range</dt><dd>{profile.budget}</dd></div><div><dt>Body type</dt><dd>{profile.body}</dd></div><div><dt>Fuel preference</dt><dd>{profile.fuel}</dd></div><div><dt>Membership</dt><dd>MAX member</dd></div></dl></article><aside className="profile-garage"><small>YOUR NEXT MOVE</small><h2>Continue the journey.</h2><img src="/vehicles/bmw-m2-g87/angle-1.jpg" alt="Rear view of BMW M2"/><a href="/max-3d">Open MAX Experience</a></aside></section>
    <section className="profile-services-v2"><header><small>03 / ACCOUNT SERVICES</small><h2>Manage every connection.</h2></header><div>{quick.map(([title,text,href],i)=><a href={href} key={title}><b>{String(i+1).padStart(2,"0")}</b><span><strong>{title}</strong><small>{text}</small></span><em>→</em></a>)}</div></section>
    {editing&&<div className="profile-edit-modal" role="dialog" aria-modal="true" aria-label="Edit profile" onMouseDown={event=>event.target===event.currentTarget&&setEditing(false)}><form onSubmit={save}><header><div><small>EDIT PROFILE</small><h2>Make MAX CARS yours.</h2></div><button type="button" onClick={()=>setEditing(false)} aria-label="Close">×</button></header><div className="avatar-editor"><div className="profile-photo small">{avatar?<img src={avatar} alt="Profile preview"/>:initials}</div><label>Upload photograph<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>upload(event.target.files?.[0])}/></label>{avatar&&<button type="button" onClick={()=>{localStorage.removeItem("max-avatar");setAvatar("")}}>Remove</button>}</div><div className="profile-form-grid"><label>Full name<input value={session.name} onChange={e=>setSession({...session,name:e.target.value})} required/></label><label>Email<input type="email" value={session.email} onChange={e=>setSession({...session,email:e.target.value})} required/></label><label>Mobile<input type="tel" inputMode="numeric" value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label>Date of birth<input type="date" value={profile.dob} onChange={e=>setProfile({...profile,dob:e.target.value})}/></label><label>City<input value={profile.city} onChange={e=>setProfile({...profile,city:e.target.value})}/></label><label>Postcode<input inputMode="numeric" value={profile.postcode} onChange={e=>setProfile({...profile,postcode:e.target.value})}/></label><label className="full">Preferred dealer<input value={profile.dealer} onChange={e=>setProfile({...profile,dealer:e.target.value})}/></label><label className="full">Preferred brands<input value={profile.brands} onChange={e=>setProfile({...profile,brands:e.target.value})}/></label><label>Budget range<input value={profile.budget} onChange={e=>setProfile({...profile,budget:e.target.value})}/></label><label>Body type<input value={profile.body} onChange={e=>setProfile({...profile,body:e.target.value})}/></label><label>Fuel preference<input value={profile.fuel} onChange={e=>setProfile({...profile,fuel:e.target.value})}/></label></div><footer><button type="button" onClick={()=>setEditing(false)}>Cancel</button><button className="primary">Save Profile</button></footer></form></div>}
  </main>;
}
