"use client";
import {useMemo,useState} from "react";
import {cars,short} from "./data";
import VehicleImage from "./VehicleImage";
import {experienceFor,experienceHref} from "./vehicle-experience";

const copy:Record<string,{eyebrow:string;title:string;intro:string}>={
  explore:{eyebrow:"DISCOVER / ALL VEHICLES",title:"The right car starts with a better search.",intro:"Explore verified MAX CARS records by body style, powertrain, price and availability."},
  search:{eyebrow:"ADVANCED VEHICLE SEARCH",title:"Search without compromise.",intro:"Combine brand, model, body style, fuel, price and 3D availability in one responsive search."},
  new:{eyebrow:"CURRENT MODEL YEAR",title:"New cars, clearly presented.",intro:"Explore new vehicles with indicative Indian ex-showroom pricing and structured specifications."},
  used:{eyebrow:"PRE-OWNED / VERIFIED RECORDS",title:"Used cars with the details that matter.",intro:"Review condition, ownership and inspection information before making an enquiry."},
  upcoming:{eyebrow:"FUTURE RELEASES",title:"What arrives next.",intro:"Track announced vehicles without confusing previews with currently available stock."},
  launched:{eyebrow:"RECENTLY LAUNCHED",title:"The newest arrivals.",intro:"Discover the latest model-year records in the MAX CARS catalogue."},
  brands:{eyebrow:"GLOBAL MARQUES",title:"Browse every brand.",intro:"Select a marque to view only its own models, variants and vehicle media."},
  budget:{eyebrow:"PRICE-LED DISCOVERY",title:"Find more within your budget.",intro:"Use clear price bands and finance estimates to shortlist realistic options."},
  offers:{eyebrow:"MAX CARS OFFERS",title:"Offers without hidden assumptions.",intro:"Review clearly labelled promotional and finance demonstrations. Final eligibility depends on the provider."},
};

export function CatalogueRoute({kind="explore",category}:{kind?:string;category?:string}){
  const c=copy[kind]||copy.explore,[q,setQ]=useState(""),[brand,setBrand]=useState(""),[fuel,setFuel]=useState(""),[sort,setSort]=useState("popular"),[priceBand,setPriceBand]=useState<[number,number]|null>(null);
  const filtered=useMemo(()=>{
    let list=cars.filter(x=>!category||x.body===category||x.category===category||x.fuel===category);
    if(kind==="new")list=list.filter(x=>x.condition==="new");if(kind==="used")list=list.filter(x=>x.condition==="used");if(kind==="upcoming")list=list.filter((_,i)=>i%6===0);if(kind==="launched")list=list.filter(x=>x.year===2026);
    if(brand)list=list.filter(x=>x.brand===brand);if(fuel)list=list.filter(x=>x.fuel===fuel);if(priceBand)list=list.filter(x=>x.price>=priceBand[0]&&x.price<priceBand[1]);if(q)list=list.filter(x=>`${x.brand} ${x.model} ${x.variant} ${x.body}`.toLowerCase().includes(q.toLowerCase()));
    return [...list].sort((a,b)=>sort==="price-low"?a.price-b.price:sort==="price-high"?b.price-a.price:b.rating-a.rating)
  },[kind,category,brand,fuel,priceBand,q,sort]);
  const brands=[...new Set(cars.map(x=>x.brand))];
  return <main className="catalogue-route"><section className="route-hero"><small>{c.eyebrow}</small><h1>{category?`${category[0].toUpperCase()+category.slice(1)} cars, considered.`:c.title}</h1><p>{c.intro}</p><a href="#results">Explore {filtered.length} vehicles ↓</a></section>
    {kind==="brands"&&<section className="brand-index">{brands.map(b=><button onClick={()=>setBrand(b)} className={brand===b?"active":""} key={b}><b>{b}</b><span>{cars.filter(c=>c.brand===b).length} model records</span></button>)}</section>}
    {kind==="budget"&&<section className="budget-bands">{([["Under ₹10 lakh",0,1e6],["₹10–20 lakh",1e6,2e6],["₹20–50 lakh",2e6,5e6],["₹50 lakh+",5e6,Number.POSITIVE_INFINITY]] as const).map(x=><button aria-pressed={priceBand?.[0]===x[1]} className={priceBand?.[0]===x[1]?"active":""} key={x[0]} onClick={()=>{setQ("");setPriceBand([x[1],x[2]]);document.getElementById("results")?.scrollIntoView({behavior:"smooth"})}}><small>CURATED RANGE</small><b>{x[0]}</b><span>View suitable vehicles →</span></button>)}</section>}
    <section className="catalogue-controls" id="results"><label>Search<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Brand, model, variant or body style"/></label><label>Brand<select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">All brands</option>{brands.map(b=><option key={b}>{b}</option>)}</select></label><label>Fuel<select value={fuel} onChange={e=>setFuel(e.target.value)}><option value="">All powertrains</option>{[...new Set(cars.map(x=>x.fuel))].map(f=><option key={f}>{f}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Highest rated</option><option value="price-low">Price: Low to High</option><option value="price-high">Price: High to Low</option></select></label><button onClick={()=>{setQ("");setBrand("");setFuel("");setPriceBand(null)}}>Clear all</button></section>
    <div className="catalogue-count">{filtered.length} matching vehicle{filtered.length===1?"":"s"}{brand?` from ${brand}`:""}</div>
    {filtered.length?<section className="catalogue-grid">{filtered.map(car=>{const experience=experienceFor(car);return <article key={car.id}><a className="catalogue-image" href={`/cars/${car.slug}`}><VehicleImage src={car.image} alt={`${car.brand} ${car.model}`} sizes="(max-width:700px) 100vw, 33vw"/></a><div><small>{car.brand.toUpperCase()} · {car.year} · {car.badge}</small><h2>{car.model}</h2><p>{car.variant}</p><dl><span><b>{short(car.price)}</b>Starting price*</span><span><b>{car.power}</b>Power</span><span><b>{car.range}</b>{car.fuel==="electric"?"Range":"Efficiency"}</span><span><b>{car.rating}/5</b>User rating</span></dl><footer><a className="primary" href={`/cars/${car.slug}`}>View Details</a>{experience.kind!=="photography"&&<a href={experienceHref(car)}>{experience.label}</a>}<a href={`/book-test-drive?car=${car.slug}`}>Test Drive</a><a href="/compare">Compare</a></footer></div></article>})}</section>:<section className="route-empty"><h2>No vehicles match these filters.</h2><p>Clear filters or explore the complete catalogue.</p><button onClick={()=>{setQ("");setBrand("");setFuel("")}}>Clear filters</button></section>}
  </main>
}

const serviceCopy:Record<string,{eyebrow:string;title:string;intro:string;fields:string[];action:string}>={
  insurance:{eyebrow:"OWNERSHIP / INSURANCE",title:"Protect the drive.",intro:"Compare indicative insurance requirements and prepare the information a provider will need.",fields:["Vehicle registration or model","City","Declared vehicle value"],action:"Create insurance estimate"},
  "book-test-drive":{eyebrow:"EXPERIENCE THE VEHICLE",title:"Book a test drive.",intro:"Choose a vehicle, preferred city and appointment date. Available times remain estimates until confirmed.",fields:["Vehicle","Preferred location","Preferred date","Full name","Email","Mobile number"],action:"Request test drive"},
  "request-quote":{eyebrow:"DEALER QUOTATION",title:"Request a clear quotation.",intro:"Send the selected vehicle or saved MAX 3D configuration to a preferred MAX CARS location.",fields:["Vehicle or configuration ID","Preferred location","Full name","Email","Mobile number"],action:"Request quotation"},
  "buy-online":{eyebrow:"ONLINE PURCHASE PROCESS",title:"From selection to delivery.",intro:"Review the purchase journey before sharing documents or confirming a reservation.",fields:["Selected vehicle","Delivery city","Preferred contact method"],action:"Start purchase enquiry"},
  contact:{eyebrow:"CONTACT MAX CARS",title:"Talk to the right team.",intro:"Ask about a vehicle, a booking, your account, a location or MAX 3D compatibility.",fields:["Full name","Email","Subject","Message"],action:"Send enquiry"},
};
export function ServiceRoute({kind}:{kind:string}){const c=serviceCopy[kind]||serviceCopy.contact,[done,setDone]=useState("");return <main className="service-route"><section><small>{c.eyebrow}</small><h1>{c.title}</h1><p>{c.intro}</p><dl><span><b>01</b>Choose the exact vehicle or service</span><span><b>02</b>Provide only required information</span><span><b>03</b>Receive a trackable reference</span></dl></section><form onSubmit={e=>{e.preventDefault();setDone(`MAX-${kind.toUpperCase()}-${Date.now().toString().slice(-6)}`)}}>{done?<div className="service-success"><b>Request received</b><h2>{done}</h2><p>Save this reference. This demonstration stores no payment information.</p><a href="/dashboard">Open dashboard →</a></div>:<><header><small>SECURE REQUEST</small><h2>Tell us what you need.</h2></header>{c.fields.map(f=><label key={f}>{f}{f==="Message"?<textarea required/>:f.includes("date")?<input type="date" min={new Date().toISOString().slice(0,10)} required/>:<input required type={f==="Email"?"email":f==="Mobile number"?"tel":"text"}/>}</label>)}<label className="consent"><input type="checkbox" required/> I agree to be contacted about this request.</label><button>{c.action}</button><p>Submitting this form does not confirm pricing, finance approval, stock or an appointment.</p></>}</form></main>}

export function CarSection({slug,section}:{slug:string;section?:string}){const car=cars.find(c=>c.slug===slug);if(!car)return <main className="route-empty"><h1>Vehicle record not found.</h1><a href="/cars">Return to Explore Cars</a></main>;if(!section)return <></>;const experience=experienceFor(car);const content:Record<string,{title:string;intro:string}>={gallery:{title:`${car.model} media gallery`,intro:"Verified vehicle media, angle labels and exact-model fallbacks."},specifications:{title:`${car.model} specifications`,intro:"Structured performance, dimensions, powertrain and safety information."},variants:{title:`${car.model} variants and pricing`,intro:"Variant-specific pricing and feature differences without mixed specifications."},ownership:{title:`${car.model} ownership cost`,intro:"Indicative finance, insurance, energy and five-year running-cost planning."},reviews:{title:`${car.model} reviews and ratings`,intro:"Owner and expert feedback, clearly separated from vehicle specifications."}};const x=content[section]||content.specifications;return <main className="car-section-route"><small>{car.brand.toUpperCase()} / {section.toUpperCase()}</small><h1>{x.title}</h1><p>{x.intro}</p><img src={car.image} alt={`${car.brand} ${car.model}`}/><section>{section==="gallery"?<a href={`/cars/${car.slug}`}>Open interactive gallery →</a>:section==="ownership"?<><b>Estimated EMI and ownership tools</b><a href={`/finance?car=${car.slug}`}>Calculate finance →</a></>:section==="reviews"?<><b>{car.rating}/5 user rating</b><p>Ratings are catalogue demonstrations and not manufacturer claims.</p></>:<dl><span><b>{car.variant}</b>Variant</span><span><b>{short(car.price)}</b>Ex-showroom from*</span><span><b>{car.power}</b>Power</span><span><b>{car.range}</b>Range / mileage</span><span><b>{car.transmission}</b>Transmission</span><span><b>{car.safety}</b>Safety</span></dl>}</section><nav><a href={`/cars/${car.slug}`}>Full vehicle details</a>{experience.kind!=="photography"&&<a href={experienceHref(car)}>{experience.label}</a>}<a href={`/book-test-drive?car=${car.slug}`}>Book test drive</a></nav></main>}
